### ISSUE TITLE
after editing a field old version is also shown

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#158]
I just updated a field, and filtered for “latest:true” but the old version is also showing.
![Image](https://github.com/user-attachments/assets/c0012122-16c3-4c01-80cc-bf340abb94b1)

The database seems in order:
![Image](https://github.com/user-attachments/assets/b5152a3b-04ab-4cf5-9653-ca3364700cd7)

It looks like the default filter for the fields is not `{"latest":true}`

Happened on the [dev (wwwint) env](https://wwwint.ebi.ac.uk/biosamples/checklist-editor/#/fields)

**Comment by snathanvj** [comment]
When I filter for latest:true , it always shows latest fields only. When unselect i.e, leave the latest box empty it shows all, when I select latest:false , it shows old fields only.

i.e.,
 latest - none slected - shows all
latest - true selected - shows latest only
latest - false selected - shows previous versions only 

is there any of this behaviour has be to be changed please let me know. Otherwise it is working as expected. @amnonkhen FYI in the screenshot you attached nothing selected for latest filter

**Comment by amnonkhen** [comment]
Thanks, @snathanvj, for the detailed check.
I also don't see it reproduce. Perhaps it was related to corrupt db data issues that have recently been fixed. Let's close this for now.
